services:
  # Playwright MCP via Proxy
  playwright-mcp:
    image: python:3.11-slim
    container_name: playwright-mcp
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /mnt/user/appdata/mcp-suite/playwright/data:/data
      - /mnt/user/appdata/mcp-suite/playwright/root:/root
      - /mnt/user/appdata/mcp-suite/playwright/npm-cache:/root/.npm
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      sh -c "
        if [ ! -f /root/.setup_done ]; then
          apt-get update &&
          apt-get install -y nodejs npm &&
          pip install --no-cache-dir mcp-proxy &&
          echo 'Installing Playwright browsers and dependencies...' &&
          npx -y playwright install chromium &&
          npx -y playwright install-deps chromium &&
          touch /root/.setup_done;
        fi &&
        mcp-proxy --port 3008 --host 0.0.0.0 -- npx -y @executeautomation/playwright-mcp-server
      "
    ports:
      - "3008:3008"
    networks:
      - mcp_network
    shm_size: '2gb'

networks:
  mcp_network:
    external: true
