services:
  playwright-mcp:
    image: mcr.microsoft.com/playwright:v1.49.1-noble
    container_name: playwright-mcp
    restart: unless-stopped
    network_mode: bridge
    working_dir: /app
    command: >
      sh -c "
        npm install -g @playwright/mcp &&
        npx @playwright/mcp --port 3008
      "
    ports:
      - "3008:3008"
    shm_size: 2gb
    environment:
      - DISPLAY=:99
